CREATE DATABASE KidReads_DB;
USE KidReads_DB;

CREATE TABLE LibraryBooks (
  ISBN VARCHAR(50) NOT NULL,
  Title VARCHAR(75) NOT NULL,
  Author VARCHAR(40) NULL,
  Description TEXT NULL,
  Available BOOLEAN NULL,
  PageCount INT NULL,
  createdAt TIMESTAMP DEFAULT NOW() ON UPDATE NOW() NULL,
  updatedAt TIMESTAMP DEFAULT NOW() ON UPDATE NOW() NULL,

  PRIMARY KEY (ISBN) 
);

CREATE TABLE LibraryBooks_Setup (
    BookId INT NOT NULL AUTO_INCREMENT,
    ISBN VARCHAR(50) NOT NULL,
    PageNumber VARCHAR(4) NULL,
    PageText TEXT NULL,
    PageFont VARCHAR(50) NULL,
    PageFontColor VARCHAR(50) NULL,
    PageFontSize VARCHAR(3) NULL,
    PageImageFilePath VARCHAR(200),
    PageAudioFilePath VARCHAR(200),
    createdAt TIMESTAMP DEFAULT NOW() ON UPDATE NOW() NULL,
    updatedAt TIMESTAMP DEFAULT NOW() ON UPDATE NOW() NULL,

    PRIMARY KEY (BookId),
    FOREIGN KEY fk_ISBN(ISBN)
    REFERENCES LibraryBooks(ISBN)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE Users (
    id INT NOT NULL AUTO_INCREMENT,
    email VARCHAR(50) NULL,
    username VARCHAR(20) NULL,
    password VARCHAR(20) NULL,
    about TEXT NULL,
    firstname VARCHAR(25) NULL,
    lastname VARCHAR(25) NULL,
    AddressStreet1 VARCHAR(50) NULL,
    AddressStreet2 VARCHAR(50) NULL,
    AddressCity VARCHAR(25) NULL,
    AddressState VARCHAR(2) NULL,
    AddressZip VARCHAR(10) NULL,
    status ENUM('active', 'inactive') DEFAULT 'active',
    last_login DATETIME NULL,
    createdAt TIMESTAMP DEFAULT NOW() ON UPDATE NOW() NULL,
    updatedAt TIMESTAMP DEFAULT NOW() ON UPDATE NOW() NULL,

    PRIMARY KEY(id)
);

CREATE TABLE ChildUsers (
    ChildId INT NOT NULL AUTO_INCREMENT,
    ParentId INT NOT NULL,
    FirstName VARCHAR(25) NULL,
    LastName VARCHAR(25) NULL,
    Birthday VARCHAR(5) NULL,
    FavoriteAnimal VARCHAR(35) NULL,
    SiteTheme VARCHAR(25) NULL,
    LastSignOn DATETIME NULL,
    createdAt TIMESTAMP DEFAULT NOW() ON UPDATE NOW() NULL,
    updatedAt TIMESTAMP DEFAULT NOW() ON UPDATE NOW() NULL,

    PRIMARY KEY (ChildId)
);

ALTER TABLE ChildUsers
    ADD FOREIGN KEY fk_parentId(ParentId)
    REFERENCES Users(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

DELIMITER #
CREATE TRIGGER populateChildBooks AFTER INSERT ON ChildUsers
FOR EACH ROW
BEGIN
  INSERT INTO ChildBooks (ISBN, ChildId)
  SELECT P.ISBN, C.ChildId
  FROM ChildUsers C JOIN
	   ParentBooks P ON P.ParentId = C.ParentId;
END#

CREATE TABLE ParentBooks (
    Id INT NOT NULL AUTO_INCREMENT,
    ISBN VARCHAR(50) NOT NULL,
    ParentId INT NOT NULL,
    LastAccessed DATETIME,
    createdAt TIMESTAMP DEFAULT NOW() ON UPDATE NOW() NULL,
    updatedAt TIMESTAMP DEFAULT NOW() ON UPDATE NOW() NULL,

    PRIMARY KEY (Id),
    FOREIGN KEY fk_ISBN(ISBN)
    REFERENCES LibraryBooks(ISBN)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
    FOREIGN KEY fk_parentId(ParentId)
    REFERENCES Users(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE ChildBooks (
    Id INT NOT NULL AUTO_INCREMENT,
    ISBN VARCHAR(50) NOT NULL,
    ChildId INT NOT NULL,
    LastAccessed DATETIME NULL,
    createdAt TIMESTAMP DEFAULT NOW() ON UPDATE NOW() NULL,
    updatedAt TIMESTAMP DEFAULT NOW() ON UPDATE NOW() NULL,

    PRIMARY KEY (Id),
    FOREIGN KEY fk_ISBN(ISBN)
    REFERENCES LibraryBooks(ISBN)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
    FOREIGN KEY fk_childId(ChildId)
    REFERENCES ChildUsers(ChildId)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);